{
 "title": "Energy",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  { "title": "Overzicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Huidig waarden",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "import \"experimental\"\n\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: now(),\n)\n\nfrom(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: now())\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"energy\" and r.meter == \"main\" and r._field == \"Total_W\")\n\n\n\n",
     "select": [
      [
       { "params": [ "Total_W" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "query": "import \"experimental\"\n\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: now(),\n)\n\nfrom(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: now())\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"AC_Watt\")\n\n"
    }
   ]
  },
  {
   "title": "Verbruik versus PV Opbrengst",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Total Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r.meter == \"main\" and r._field == \"Total_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "Total_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"AC_Watt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({\n      r with\n      _value: -r._value\n    })\n  )",
     "select": [
      [
       { "params": [ "Total_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Totaal verbruik",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "import \"experimental\"\n\nmaxStop = if v.timeRangeStop > now() then now() else v.timeRangeStop\nlimitedStop = experimental.addDuration(\n    d: 2m,\n    to: v.timeRangeStart,\n)\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: maxStop,\n)\n\n// ----\n\nexportmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Export_kWh\")\n  |> first()\n\nexportmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Export_kWh\")\n  |> last()\n\nexporttotal = join(tables: {a: exportmin, b: exportmax}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_b - r._value_a }))\n  |> map(fn: (r) => ({ r with _x: \"x\" }))\n  \n// ----\n\nsolarmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"total_yield\")\n  |> first()\n\nsolarmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"total_yield\")\n  |> last()\n\nsolartotal = join(tables: {a: solarmin, b: solarmax}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_b - r._value_a }))\n  |> map(fn: (r) => ({ r with _x: \"x\" }))\n\n// ----\n\nselfusage = join(tables: {a: solartotal, b: exporttotal}, on: [\"_x\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_a - r._value_b }))\n  |> map(fn: (r) => ({ r with _x: \"x\" }))\n\n// ----\n\nimportmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Import_kWh\")\n  |> first()\n\nimportmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Import_kWh\")\n  |> last()\n\nimporttotal = join(tables: {a: importmin, b: importmax}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_b - r._value_a }))\n  |> map(fn: (r) => ({ r with _x: \"x\" }))\n\n//-------\n\njoin(tables: {a: selfusage, b: importtotal}, on: [\"_x\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _bruto: r._value_a + r._value_b }))",
     "select": [
      [
       { "params": [ "L1_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "import \"experimental\"\n\nmaxStop = if v.timeRangeStop > now() then now() else v.timeRangeStop\nlimitedStop = experimental.addDuration(\n    d: 2m,\n    to: v.timeRangeStart,\n)\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: maxStop,\n)\n\n\nmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Import_kWh\")\n  |> first()\n\nmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Import_kWh\")\n  |> last()\n\n\njoin(tables: {min: min, max: max}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _netto: r._value_max - r._value_min }))\n\n\n\n"
    }
   ]
  },
  {
   "title": "PV",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "import \"experimental\"\n\nmaxStop = if v.timeRangeStop > now() then now() else v.timeRangeStop\nlimitedStop = experimental.addDuration(\n    d: 2m,\n    to: v.timeRangeStart,\n)\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: maxStop,\n)\n\nsolarmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"total_yield\")\n  |> first()\n\nsolarmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"total_yield\")\n  |> last()\n\njoin(tables: {a: solarmin, b: solarmax}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _bruto: r._value_b - r._value_a }))",
     "select": [
      [
       { "params": [ "L1_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "import \"experimental\"\n\nmaxStop = if v.timeRangeStop > now() then now() else v.timeRangeStop\nlimitedStop = experimental.addDuration(\n    d: 2m,\n    to: v.timeRangeStart,\n)\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: maxStop,\n)\n\n// ----\n\nexportmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Export_kWh\")\n  |> first()\n\nexportmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Export_kWh\")\n  |> last()\n\njoin(tables: {a: exportmin, b: exportmax}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _injection: r._value_b - r._value_a }))"
    },
    {
     "query": "import \"experimental\"\n\nmaxStop = if v.timeRangeStop > now() then now() else v.timeRangeStop\nlimitedStop = experimental.addDuration(\n    d: 2m,\n    to: v.timeRangeStart,\n)\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: maxStop,\n)\n\n// ----\n\nexportmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Export_kWh\")\n  |> first()\n\nexportmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"Total_Export_kWh\")\n  |> last()\n\nexporttotal = join(tables: {a: exportmin, b: exportmax}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_b - r._value_a }))\n  |> map(fn: (r) => ({ r with _x: \"x\" }))\n\n\n// -----\n\nsolarmin = from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: limitedStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"total_yield\")\n  |> first()\n\nsolarmax = from(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"total_yield\")\n  |> last()\n\nsolartotal = join(tables: {a: solarmin, b: solarmax}, on: [\"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_b - r._value_a }))\n  |> map(fn: (r) => ({ r with _x: \"x\" }))\n\n// -----\n\njoin(tables: {a: solartotal, b: exporttotal}, on: [\"_x\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_b / r._value_a }))\n  |> map(fn: (r) => ({ r with _ratio: 1.0 - r._value }))"
    }
   ]
  },
  { "title": "Verbruik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Huidig verbruik per fase",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "import \"experimental\"\n\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: now(),\n)\n\nfrom(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: now())\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"energy\" and r.meter == \"main\" and (r._field == \"L1_W\" or r._field == \"L2_W\" or r._field == \"L3_W\"))\n",
     "select": [
      [
       { "params": [ "L1_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vermogenspieken per kwartier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "  from(bucket: \"home/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Total_W\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Huidig amperage per fase",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "import \"experimental\"\n\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: now(),\n)\n\nfrom(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: now())\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"energy\" and r.meter == \"main\" and (r._field == \"L1_A\" or r._field == \"L2_A\" or r._field == \"L3_A\"))\n",
     "select": [
      [
       { "params": [ "L1_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbruik per fase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Total Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r.meter == \"main\" and r._field == \"L1_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "Total_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r.meter == \"main\" and r._field == \"L2_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "Total_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy\" and r._field == \"L3_W\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "Total_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Zonnepanelen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Huidige opbrengst per dakdeel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "import \"experimental\"\n\nlimitedStart = experimental.subDuration(\n    d: 2m,\n    from: now(),\n)\n\nfrom(bucket: \"home/autogen\")\n  |> range(start: limitedStart, stop: now())\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"solar\" and (r._field == \"DC_Watt_A\" or r._field == \"DC_Watt_B\"))\n",
     "select": [
      [
       { "params": [ "L1_W" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Opbrengst per dakdeel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"DC_Watt_A\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    },
    {
     "query": "from(bucket: \"home/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"solar\" and r._field == \"DC_Watt_B\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    },
    { "target": "sun_altitude" }
   ]
  }
 ]
}